### ISSUE TITLE
Why use gcloud alpha?

### ISSUE THREAD

**Issue by zackijack** [CircleCI-Public/gcp-gcr-orb#13]
### Orb version

0.0.7

### What happened

I just want to ask, why you use alpha version `gcloud alpha auth configure-docker` instead of just `auth configure-docker`?

BTW, thanks for making this orb

**Comment by iynere** [comment]
@zackijack feel free to submit a PR to change—seems like an easy fix

**Comment by iynere** [comment]
@zackijack @felicianotech the command actually needs `gcloud alpha` https://circleci.com/gh/CircleCI-Public/gcp-gcr-orb/177

**Comment by felicianotech** [comment]
@iynere Oh hmm.

I'll revert and add a note to the source so that we know this in the future.

**Comment by iynere** [comment]
its possible the syntax for `gcloud` is different than it is for `gcloud alpha`—feel free to look into that @felicianotech @zackijack

**Comment by felicianotech** [comment]
The build are running an old version of `gcloud`. This is causing this issue. Will fix that (in a new issue) before revisiting this.

**Comment by iynere** [comment]
no longer using alpha
