### ISSUE TITLE
Old version of gcloud

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/gcp-gcr-orb#16]
The CircleCI builds are using an old version of `gcloud`. This needs to be fixed.

**Comment by iynere** [comment]
this sho9uldn't be here, it shoudl be in gcp-cli-orb

**Comment by iynere** [comment]
https://github.com/CircleCI-Public/gcp-cli-orb/issues/8

**Comment by felicianotech** [comment]
@iynere We don't necessarily know that yet. I was going to create an issue in both repos and link them until we determine the exact issue.

This here is also so if someone comes here with this issue because they aren't using the CLI orb directly, they can see this issue and know something has already been filed.

**Comment by felicianotech** [comment]
And the issue was in this repo.

We're using an old version of the GCP CLI orb. Creating a PR now.
