### ISSUE TITLE
user circleci can't push to GCR without sudo

### ISSUE THREAD

**Issue by zackijack** [CircleCI-Public/gcp-gcr-orb#19]
### Orb version

0.3.0

### What happened

After successfully running `gcr-auth` command, I always get this error when I want to push image to GCR:
```
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

### Expected behavior

After successfully running `gcr-auth` command, I can push image to GCR with circleci user.

### My Guess
When I SSH,  I found /home/circleci/.docker folder empty, while /root/.docker had `config.json`.
I think this is because `gcloud auth configure-docker` was run with sudo.
``` sh
# Set sudo to work whether logged in as root user or non-root user
if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

# configure Docker to use gcloud as a credential helper
mkdir -p /home/circleci/.docker
$SUDO gcloud auth configure-docker --quiet --project $<<parameters.google-project-id>>
```
so giving the user circleci ownership to /home/circleci/.docker is useless, because after all the user still can't push the image, except with sudo of course.
``` sh
# if applicable, provide circleci user access to the docker config file
if [[ -d /home/circleci/.docker ]]; then
$SUDO chown circleci:circleci /home/circleci/.docker -R
fi
if [[ -d /home/circleci/.config ]]; then
$SUDO chown circleci:circleci /home/circleci/.config -R
fi
```

**Comment by benjlevesque** [comment]
@zackijack , I'm having the same issue. I removed the `gcr-auth` step and I use the command directly (without sudo): 
```bash
- gcp-cli/install
- gcp-cli/initialize
- run: gcloud auth configure-docker  --project $GOOGLE_PROJECT_ID --quiet
```

**Comment by iynere** [comment]
thanks ! @zackijack sounds like an easy fix—that line doesn't seem to need sudo

**Comment by iynere** [comment]
@zackijack this should fix it: https://github.com/CircleCI-Public/gcp-gcr-orb/commit/9de3d284f6408f0d1f74b7c672468de7a449a2e0

**Comment by iynere** [comment]
@zackijack @benjlevesque `circleci/gcp-gcr@0.4.0`

**Comment by zackijack** [comment]
@benjlevesque yes I also use the same method as you

**Comment by zackijack** [comment]
Thanks @iynere, its worked!

But I think there are some commands that are no longer needed, so it can be simplified. if you don't mind, I have submitted a pull-request #22 for that.
