### ISSUE TITLE
Config files using the gcp-gcr orb are invalid

### ISSUE THREAD

**Issue by rikbw** [CircleCI-Public/gcp-gcr-orb#36]
### Orb version

0.7.1

### What happened

Config files are no longer valid if they use the `gcp-gcr: circleci/gcp-gcr@0.7.1` orb. A large error is generated that seems to be related to the docker orb. This can be replicated locally by using `circleci config validate`. 

### Expected behavior

Using the gcp-gcr orb should not make config files invalid.

**Comment by lokst** [comment]
@rikbw Could you try again by pushing a new commit? This looks to be caused by an issue with a recent deployment in the CircleCI backend, but it should be resolved now.

**Comment by barakreif** [comment]
@lokst  we just did, similar error.

**Comment by thiagorp** [comment]
The same thing is happening to me

**Comment by rikbw** [comment]
> @rikbw Could you try again by pushing a new commit? This looks to be caused by an issue with a recent deployment in the CircleCI backend, but it should be resolved now.

Right now, the issue seems to be resolved indeed. I'll close this issue.
