### ISSUE TITLE
Remove dependency on circleci user

### ISSUE THREAD

**Issue by wrdls** [CircleCI-Public/gcp-gcr-orb#4]
I tried to use this orb with the `google/cloud-sdk` image but it doesn't have the circleci user which makes chown fail:

https://github.com/CircleCI-Public/gcp-gcr-orb/blob/aeaf1c7036d76b643d0d605d87a93b8bc1f9b277/src/%40orb.yml#L69

My quick fix is to add the circleci user:
```
      - run: useradd circleci
```

I think it would be better to make use of `$USER` and `$HOME`.

**Comment by freeyoung** [comment]
+1

**Comment by iynere** [comment]
@wrdls wow, yes, we need to fix this. thank you !

**Comment by iynere** [comment]
@wrdls @freeyoung apologies for the very long delay—would y'all mind taking a look at this PR to fix this ? https://github.com/CircleCI-Public/gcp-gcr-orb/pull/20

**Comment by iynere** [comment]
patched in `circleci/gcp-gcr@0.5.0`
