### ISSUE TITLE
Need a timeout parameter, just like in the AWS ECR Orb

### ISSUE THREAD

**Issue by ahavriliuc-zuum** [CircleCI-Public/gcp-gcr-orb#41]
## Describe Request:
Sometimes, lengthy builds need more that 10 minutes with no output. Currently, The AWS ECR orb provides this option, while the GCR orb does not.

## Examples of proposed solution:

  gcp-gcr-orb-build-and-push-image-cmd:
    steps:
      - checkout
      - gcp-gcr-orb/gcr-auth
      - gcp-gcr-orb/build-image:
          image: ${CIRCLE_PROJECT_REPONAME}
          tag: ${FINAL_IMAGE_TAG}
          extra_build_args: --build-arg APP_ENV=${APP_ENV}
          **no_output_timeout: 30m**

## Supporting Documentation Links:

Docs for AWS ECR Orb:

https://circleci.com/orbs/registry/orb/circleci/aws-ecr

**Comment by cristizuum** [comment]
@gmemstr any progress on this issue?

**Comment by gmemstr** [comment]
The AWS ECR orb uses a custom script for building a Docker image, but this orb uses the [docker orb](https://github.com/CircleCI-Public/docker-orb) to build, which does not have a no_output_timeout parameter either. That would need to be added before we go ahead with this.
