### ISSUE TITLE
Not working anymore under Ubuntu 22.04

### ISSUE THREAD

**Issue by clementprevot** [CircleCI-Public/gcp-gcr-orb#57]
## Orb version:

0.15.0

## What happened:

I tried to update the docker base image from `cimg/base:2022.08` to `cimg/base:2022.09`.
This new version now uses Ubuntu 22.04 as the default version (latest LTS + 4 month) and my guess is that (like many other OS/distrib) this version of Ubuntu got rid of Python < 3.10.

Now running the orb (with `gcp-gcr/gcr-auth`) gives this error: 

> ERROR: gcloud failed to load: module 'collections' has no attribute 'MutableMapping'
>     gcloud_main = _import_gcloud_main()
>     import googlecloudsdk.gcloud_main
>     from googlecloudsdk.api_lib.iamcredentials import util as iamcred_util
>     from googlecloudsdk.api_lib.util import exceptions
>     from googlecloudsdk.core.resource import resource_printer
>     from googlecloudsdk.core.resource import config_printer
>     from googlecloudsdk.core.resource import resource_printer_base
>     from googlecloudsdk.core.resource import resource_projector
>     from google.protobuf import json_format as protobuf_encoding
>     from google.protobuf import symbol_database
>     from google.protobuf import message_factory
>     from google.protobuf import reflection
>     from google.protobuf.internal import python_message as message_impl
>     from google.protobuf.internal import containers
>     MutableMapping = collections.MutableMapping
> 
> This usually indicates corruption in your gcloud installation or problems with your Python interpreter.
> 
> Please verify that the following is the path to a working Python 2.7 or 3.5+ executable:
>     /usr/bin/python3
> 
> If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 or 3.5+ executable.
> 
> If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
>     https://cloud.google.com/sdk/
> 
> Exited with code exit status 1

## Expected behavior:

It should work fine.

## Additional Information:

/

**Comment by danopia** [comment]
It looks like `cimg/node:lts` just rolled over today to python 3.10, which broke a lot of my pipelines.

Please update the embedded gcp-cli orb reference!

**Comment by danopia** [comment]
It appears that gcp-gcr-orb `0.15.1` includes the fix for this.

**Comment by david-montano-circleci** [comment]
I was not able to replicate this error which seems to have been solved after updating the gcp-cli tool.
Closing this issue given that it is deprecated.
