### ISSUE TITLE
docker push failing with 0.15.1 patch

### ISSUE THREAD

**Issue by michael-robertson** [CircleCI-Public/gcp-gcr-orb#65]
## Orb version: 

0.15.1

## What happened:

Our pipelines started failing with the release of gcp-gcr orb 0.15.1

We have been using `gcp-gcr: circleci/gcp-gcr@0.15` with no issues prior.

The error step output:
```
#!/bin/bash -eo pipefail
#!/bin/bash 

IFS="," read -ra DOCKER_TAGS <<< "$ORB_EVAL_TAG"
PROJECT_ID="${!ORB_ENV_PROJECT_ID}"

for tag_to_eval in "${DOCKER_TAGS[@]}"; do
    TAG=$(eval echo "$tag_to_eval")
    docker push "$ORB_VAL_REGISTRY_URL/$PROJECT_ID/$ORB_VAL_IMAGE:$TAG"
done

if [ -n "$ORB_VAL_DIGEST_PATH" ]; then
    mkdir -p "$(dirname "$ORB_VAL_DIGEST_PATH")"
    SAMPLE_FIRST=$(eval echo "${DOCKER_TAGS[0]}")
    docker image inspect --format="{{index .RepoDigests 0}}" "$ORB_VAL_REGISTRY_URL/$PROJECT_ID/$ORB_VAL_IMAGE:$SAMPLE_FIRST" > "$ORB_VAL_DIGEST_PATH"
fi

invalid reference format: repository name must be lowercase

Exited with code exit status 1
CircleCI received exit code 1
```

This appears to be the contents of the new `push-image.sh` file that [appeared in 0.15.1](https://github.com/CircleCI-Public/gcp-gcr-orb/compare/v0.15.0...v0.15.1#).

Re-run with SSH showed that the `ORB_VAL_*` environment variables were not set, so they were not getting passed through. This explains the cryptic docker error at least.

Also notable is that we don't use the default machine executor, but prefer instead docker (cimg/base:2022.08) for performance and cost reasons. This should not make a difference, I would expect, but there could be some unexpected interaction beyond my perception.

## Expected behavior:

Working as before.

Suggestion: This was a significant refactor, not a patch, should have been `0.16` really.

## Additional Information:

Workaround is currently pinning to `0.15.0`, but would rather not.

**Comment by cvitan** [comment]
Second this, this broke all our workflows.

**Comment by bryceAebi** [comment]
+1

**Comment by flurdy** [comment]
6 months on, still the same error and no other patch has been released.

**Comment by danopia** [comment]
And there's been an open PR from the community since then: #67

My understanding is that this occurs when shell variables like `${CIRCLE_PROJECT_REPONAME}` are used in the `image:` field. One workaround is using a [Pipeline Variable](https://circleci.com/docs/pipeline-variables/) instead. Unfortunately, I'm not aware of a Pipeline Variable which matches `CIRCLE_PROJECT_REPONAME`.

I don't think running old versions on purpose, so I've been replacing `${CIRCLE_PROJECT_REPONAME}` with the repo's actual names :/
