### ISSUE TITLE
Using gcp-gcr orb with OIDC auth from gcp-cli orb?

### ISSUE THREAD

**Issue by danopia** [CircleCI-Public/gcp-gcr-orb#68]
## Describe Request:

I am using this gcp-gcr orb to push container images to GCR.

I would like to use [OpenID Connect tokens](https://circleci.com/docs/openid-connect-tokens/) to authenticate to GCR.

This seems to be impossible with gcp-gcr's `gcr-auth` command as it always calls `gcp-cli/setup` without plumbing the OIDC-related options:

https://github.com/CircleCI-Public/gcp-gcr-orb/blob/ee205ade0b610ce8412f0513dc936dcf7bc7504a/src/commands/gcr-auth.yml#L36-L48

## Examples:

The gcp-cli command is pretty straightforward:

```
          - gcp-cli/setup:
              use_oidc: true
```

There's other parameters but they have defaults, so it's just the boolean flag that needs toggling at a bare minimum.

## Supporting Documentation Links:

https://circleci.com/docs/openid-connect-tokens/

**Comment by otherguy** [comment]
I'm voting for that too. Especially after the incident in January, and [CircleCI pushing the use of OIDC tokens](https://circleci.com/docs/openid-connect-tokens/), this is pretty much a requirement.

**Comment by otherguy** [comment]
@CircleCI any progress on this?

**Comment by girish97115** [comment]
I have opened a PR for the same issue. Can someone look into this ?

**Comment by girish97115** [comment]
Any update on this ?

**Comment by otherguy** [comment]
@circleci has this been abandoned?

**Comment by danopia** [comment]
I've successfully rolled out OIDC auth using 0.16 and the new `use_oidc: true` parameter.

**Comment by otherguy** [comment]
@danopia but have you used it with GCR?

**Comment by danopia** [comment]
Yes, the PR linked above got a release in January and this orb has oidc now. 

Of course gcr is on its way out but that's not what I'm working on today.
