### ISSUE TITLE
The version installed (451.0.0) differs from the version requested (451.0.1)

### ISSUE THREAD

**Issue by xiaoyutww** [CircleCI-Public/gcp-gcr-orb#74]
![image](https://github.com/CircleCI-Public/gcp-gcr-orb/assets/108644861/affc0e30-0b4e-4e90-853e-79f17e5a69a8)

**Comment by david-montano-circleci** [comment]
`sudo` is now not mandatory to install gcloud in the latest version of this orb.
If this persists please report it again with more information about your specific scenario.
Thank you!
