### ISSUE TITLE
The version installed (458.0.1) differs from the version requested (459.0.0). Uninstalling v458.0.1

### ISSUE THREAD

**Issue by Cyronlee** [CircleCI-Public/gcp-gcr-orb#75]
## Orb version:

orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.3
  cloudrun: circleci/gcp-cloud-run@1.0.2

## What happened:

Error
```http
The version installed (458.0.1) differs from the version requested (459.0.0).
Uninstalling v458.0.1...
sudo is required to uninstall the Google Cloud SDK.
Please install it and try again.
Failed to uninstall the current version.

Exited with code exit status 1
```

## Expected behavior:

No error

**Comment by EricRibeiro** [comment]
The error message says:

> sudo is required to uninstall the Google Cloud SDK.

You are likely using an image that does not have `sudo` installed. You must install `sudo` yourself or use an image that has it.

**Comment by Cyronlee** [comment]
It actually went back to normal after a few days, I was curious if there was a cache that could be cleared manually

**Comment by EricRibeiro** [comment]
Not as far as I know. For now I'll close the issue but I'm happy to re-open it should the problem surface again.
