### ISSUE TITLE
Change image used because of depreciation

### ISSUE THREAD

**Issue by b0uh** [CircleCI-Public/gcp-gcr-orb#78]
## Orb version:

Any version

## What happened:
Today (March 3rd) this orb is not working because of the ongoing [brownout](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177/21)  The image used by this orb is [`ubuntu-2004`](https://github.com/CircleCI-Public/gcp-gcr-orb/blob/3af4d141795a240b32f6abd0918b80649c5381f0/src/executors/default.yml#L4) and it is deprecated.

## Expected behavior:

I would expect this orb to be working since it is maintained by CircleCI and you are aware on the depreciation and brownout.

**Comment by brentmmarks** [comment]
This image is not deprecated current will still be supported

**Comment by auroaj** [comment]
@brentmmarks , unfortunately, no:
https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
<img width="465" alt="Screenshot 2024-03-04 at 15 09 21" src="https://github.com/CircleCI-Public/gcp-gcr-orb/assets/694789/71eb208c-151b-4dbf-92d4-d1a78dd9ef04">
