### ISSUE TITLE
Multiple tags support

### ISSUE THREAD

**Issue by davilag** [CircleCI-Public/gcp-gcr-orb#8]
### Orb version
0.0.4

### What happened
If I inform in the `tag` parameter more than one value separated with commas.

### Expected behavior
The pushed image should be tagged with all those tags informed in the `tag` parameter

**Comment by iynere** [comment]
added in `circleci/gcp-gcr@0.6.0` (note: you will have to run the `tag-image` command or `add-image-tag` job multiple times—feel free to submit a PR if you'd like to make a modification that supports multiple tags via a single parameter @davilag)
